### PR TITLE
init kafka support

### PR DESCRIPTION
**Pull request by antarus**
@pascalgrimaud @PierreBesson 
Start kafka support for upgrade to Spring Cloud Edgware https://github.com/jhipster/generator-jhipster/issues/6755

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
What's the plan here? Drop Kafka from JHipster to do it here?
@PierreBesson : what do you think?

**Comment by antarus** [comment]
I think removing kafka support from the main generator is a big job, and as Julien often says, the focus is on issues.
In my opinion it is necessary to do already what the generator does in this module, to test it, to validate and to suppress little by little in the main generator, beginning to suppress kafka of the questions.

**Comment by pascalgrimaud** [comment]
Agree with you.
Yes, our main priority is to close issue, there are too much these last days

**Comment by jdubois** [comment]
+1
And we need to look at the stats: popular options should be in the
generator

Le 1 déc. 2017 9:23 AM, "Pascal Grimaud" <notifications@github.com> a
écrit :

**Comment by antarus** [comment]
I want to help, but since for me, jhipster and spring-boot are quite recent there is plenty of anomaly for which I don' understand enough global architecture and link between all component.
I do the PR issues of my level..so not much lol

**Comment by pascalgrimaud** [comment]
No worry @antarus !
Everyone started by little PR, as I did. Every little PR is always welcome!

The most important thing is simply contributing, no need to do BIG pull request, for example:
- comment ticket, give your opinion / solution
- review code
- little PR: format code, polish, typo in text
- etc

Each time you contribute, you will learn something new.

Remember: it's open source, we do it on our free time, because we love open source ;-)

**Comment by pascalgrimaud** [comment]
I'm closing this as Kafka will stay in main generator.
I believe Kafka is a must have in Microservices Architecture 
A lot of improvement have been done, and I'll do more when I have time

**Pull request closed without merging**
