### PR TITLE
Add Missing Ownership Information to License

### PR DESCRIPTION
**Pull request by SudharakaP**
Add missing ownership information to license file :smile:

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
oh noes!!!! it's not me, I never use this module lol

**Comment by murdos** [comment]
FYI I don't think we're supposed to change this line, since it's in the `APPENDIX: How to apply the Apache License to your work` section.

**Comment by pascalgrimaud** [comment]
Anyway, this repository should be "archived" as it's not maintain anymore...
What do you think ?

**Comment by SudharakaP** [comment]
> FYI I don't think we're supposed to change this line, since it's in the `APPENDIX: How to apply the Apache License to your work` section.

@murdos : Ah, you are correct. Therefore I am closing this pull request.

**Comment by murdos** [comment]
@pascalgrimaud : I used it for my previous project, I think it's useful. 
I don't think it requires a lot of maintenance, It probably mainly needs an update of spring cloud dependencies.

**Comment by pascalgrimaud** [comment]
ok so let this project like this today, no need to put in archive

**Pull request closed without merging**
