### PR TITLE
Forbidden kafka

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
It's so strange...
yarn test -> ok
gulp test -> ko

it should be the same!

**Comment by pascalgrimaud** [comment]
I revert the tests, will check it later

**Comment by antarus** [comment]
Sorry I do not know enough node, gulp and yarn

**Comment by pascalgrimaud** [comment]
The reason why it didn't pass with Gulp is probably: https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/blob/master/gulpfile.js#L30-L43

So after thinking, I will probably remove completely Gulp. There is no real value, excepting for release.

**Comment by antarus** [comment]
Do as you want I do not know enough..

**Comment by pascalgrimaud** [comment]
Completely out of subject: are you in Paris ?
If yes, there is a JHipster the 12th december. Maybe you can join the
meetup for discovering the community ?

I won't probably be there, I have a big release in production for my
current client :-(

**Comment by deepu105** [comment]
Yes please remove gulp. I'll change the config for module generator to do
the same task just using npm

**Comment by pascalgrimaud** [comment]
I'm merging this, and will remove gulp in another PR

**Comment by antarus** [comment]
@pascalgrimaud 
Yes, I am in Paris.
I see a meetup on December 6 but not the 12 on https://www.meetup.com/
But yes it could be nice to participate;)

**Pull request merged**
