### PR TITLE
Adds functions to CRUD on yaml file

### PR DESCRIPTION
**Pull request by antarus**
Adds functions to read a property from a yaml file, update , add and delete it.
The 'rewriteYamlFile' function breaks all formatting, and removes comments from the yaml file.
It's temporary, I have to find another method.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I'm testing this, after merging: as it's in dev, so we can do it :)

I noticed that the application yaml files are totally edited:
- we lost comments -> it shouldn't
- the indent is 2, instead of 4: it can be fixed by
```
        const dump = jsyaml.safeDump(data, {
            'indent': 4
        });
```

**Comment by antarus** [comment]
Yes...
I know, I'm looking for a method to edit the original file rather than rewrite everything.
I had not seen for null values. thanks

**Comment by pascalgrimaud** [comment]
What do you think for simply adding this, at the end of application yaml file:
```
spring.cloud.stream.default.contentType: application/json
spring.cloud.stream.bindings.input.destination: topic-jhipster
spring.cloud.stream.bindings.output.destination: topic-jhipster
spring.cloud.stream.bindings.rabbit.bindings.output.producer.routingKeyExpression: headers.title
```

It should work, not so elegant because it's not consistent with the other properties, but far easier!

**Comment by pascalgrimaud** [comment]
I confirm, it works :)

**Comment by antarus** [comment]
Yes easier, but if the file already contains a spring cloud, Spring will merge alone? I am not sure.

I would like to spend some time on it, because eventually, these functions could be migrated into the base generator and useful to all modules.

**Comment by pascalgrimaud** [comment]
Only tried with monolith, let me try with microservices

Yes, these functions will be usefull in main generator-jhipster

**Comment by antarus** [comment]
For the moment, I arrive has kept the formatting and comments in the following cases:
- add properties to the beginning or end of yaml file.
- adding properties before another existing property (for example before application: (and its comments)

To do :
-Manage the case where one of the parents already exists in the file and integrate it in
- Add yaml properties after another property

I cant PR at work, so tonight for the code.

**Comment by pascalgrimaud** [comment]
Same, I can't PR at work :laughing:

**Pull request merged**
